{% set name = "fenics-basix" %}
{% set version = "0.3.1" %}

{% set cmake_args = "$CMAKE_ARGS" %}  # [not win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FEniCS/basix/archive/refs/heads/main.tar.gz
  # url: https://github.com/FEniCS/basix/archive/v{{ version }}.tar.gz
  # sha256: 9b148fd2a5485c94011fc6ca977ebdef0e51782a62b3654fc044f35b60e2bd07

requirements:
  run:
    - fenics-libbasix
    - fenics-basix-python

build:
  skip: True  # [py<37]
  number: 0

outputs:
  - name: fenics-libbasix
    build:
      number: 4
      script:
        - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug {{ cmake_args }} -B build-dir -S ./cpp
        - cmake --build build-dir
        - cmake --install build-dir

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.16.0
        - ninja
      host:
        - libblas
        - liblapack
        - xtl
        - xtensor
      run:
        # - {{ compiler('cxx') }}  # [linux]
        # - libblas
        # - liblapack
        - xtl
        - xtensor
        # - python
        # - numpy
        # - setuptools
    test:
      requires:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - ninja
      source_files:
        - demo/cpp/demo_create_and_tabulate
      commands:
        - test -f ${PREFIX}/lib/libbasix${SHLIB_EXT}  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\teuchoscore.lib exit 1  # [win]
        - ldd ${PREFIX}/lib/libbasix${SHLIB_EXT}
        - cmake -G Ninja {{ cmake_args }} -B build-dir -S demo/cpp/demo_create_and_tabulate
        - cmake --build build-dir
        # - "LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH ./build-dir/demo_create_and_tabulate"  # [unix]

  - name: fenics-basix-python
    build:
      script: $PYTHON -m pip -vv install --no-deps --no-cache ./python
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - ninja
        - python
      host:
        - {{ pin_subpackage('fenics-libbasix', exact=True) }}
        - python
        - pip
        - pybind11
        - xtl
        - xtensor
      run:
        - {{ pin_subpackage('fenics-libbasix', exact=True) }}
        - python
        - numpy
    test:
      imports:
        - basix
      requires:
        - pytest
        - pytest-xdist
        - setuptools
        - sympy
      source_files:
        - test
      commands: pytest -v -n auto test

  - name: fenics-libbasix
    build:
      number: 4
      script:
        - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug {{ cmake_args }} -B build-dir -S ./cpp
        - cmake --build build-dir
        - cmake --install build-dir

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.16.0
        - ninja
      host:
        - libblas
        - liblapack
        - xtl
        - xtensor
      run:
        # - {{ compiler('cxx') }}  # [linux]
        # - libblas
        # - liblapack
        - xtl
        - xtensor
        # - python
        # - numpy
        # - setuptools
    test:
      requires:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - ninja
      source_files:
        - demo/cpp/demo_create_and_tabulate
      commands:
        - test -f ${PREFIX}/lib/libbasix${SHLIB_EXT}  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\teuchoscore.lib exit 1  # [win]
        - ldd ${PREFIX}/lib/libbasix${SHLIB_EXT}
        - cmake -G Ninja {{ cmake_args }} -B build-dir -S demo/cpp/demo_create_and_tabulate
        - cmake --build build-dir
        # - "LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH ./build-dir/demo_create_and_tabulate"  # [unix]
about:
  home: https://github.com/FEniCS/basix
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'FEniCS finite element basis evaluation library'
  description: |
    Basix is a finite element definition and tabulation runtime library.
  doc_url: https://docs.fenicsproject.org/basix/main/
  dev_url: https://github.com/FEniCS/basix/v{{ version }}

extra:
  recipe-maintainers:
    - chrisrichardson
    - garth-wells
    - mscroggs
