{% set name = "fenics-ffcx" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/FEniCS/ufl/archive/v{{ version }}.tar.gz
  url: https://github.com/FEniCS/ffcx/archive/refs/heads/main.zip
  # sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9

build:
  skip: True  # [py!=38]
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-dependencies"

requirements:
  host:
    - python
    - pip
    - fenics-basix
    - fenics-ufl
  run:
    - cffi
    - fenics-basix
    - fenics-ufl
    - numpy
    - python

test:
  requires:
    - pip
    - pytest
  source_files:
    - test
  commands:
    - pip check
    - pytest -v test

about:
  home: https://github.com/FEniCS/ffcx
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'Next generation FEniCS Form Compiler'
  description: |
    FFCx is a compiler for finite element variational forms. From a
    high-level description of the form in the Unified Form Language
    (UFL), it generates efficient low-level C code that can be used to
    assemble the corresponding discrete operator (tensor).
  doc_url: https://docs.fenicsproject.org/ffcx/main/
  dev_url: https://github.com/FEniCS/ffcx

extra:
  recipe-maintainers:
    - chrisrichardson
    - garth-wells
    - jhale
    - michalhabera
