{% set name = "fenics-ufl" %}
{% set version = "2021.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/FEniCS/ufl/archive/v{{ version }}.tar.gz
  url: https://github.com/FEniCS/ufl/archive/refs/tags/{{ version }}.tar.gz
  # sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - numpy
    - python

test:
  requires:
    - pip
    - pytest
  source_files:
    - test
  commands:
    - pip check
    - pytest -v test

about:
  home: https://github.com/FEniCS/ufl
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'Unified Form Language (UFL) for finite element forms'
  description: |
    The Unified Form Language (UFL) is a domain specific language for
    declaration of finite element discretizations of variational forms.
    More precisely, it defines a flexible interface for choosing finite
    element spaces and defining expressions for weak forms in a notation
    close to mathematical notation.
  doc_url: https://fenics.readthedocs.io/projects/ufl
  dev_url: https://github.com/FEniCS/ufl

extra:
  recipe-maintainers:
    - chrisrichardson
    - garth-wells
    - jhale
    - michalhabera
