{% set name = "fenics-basix" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FEniCS/basix/archive/refs/heads/main.zip
  # url: https://github.com/FEniCS/basix/archive/v{{ version }}.tar.gz
  # sha256: 9b148fd2a5485c94011fc6ca977ebdef0e51782a62b3654fc044f35b60e2bd07

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - pybind11
  host:
    - blas
    - lapack
    - python
    - pip
    - scikit-build
    - xtensor
    - xtl
  run:
    - numpy
    - python

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  # imports:
  #   - simplejson
  #   - simplejson.tests
  # For python packages, it is useful to run pip check. However, sometimes the
  # metadata used by pip is out of date. Thus this section is optional if it is
  # failing.
  requires:
    - pytest
  commands:
    - pytest test

about:
  home: https://github.com/FEniCS/basix
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'FEniCS finite element basis evaluation library'
  # The remaining entries in this section are optional, but recommended.
  description: |
    Basix is a finite element definition and tabulation runtime library.
  doc_url: https://docs.fenicsproject.org/basix/main/
  dev_url: https://github.com/FEniCS/basix

extra:
  recipe-maintainers:
    - chrisrichardson
    - garth-wells
    - mscroggs
